package Ventana;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.JOptionPane;

public class IniciarSesion extends javax.swing.JFrame {

   
    public IniciarSesion() {
        initComponents();
        
        this.setLocationRelativeTo(null);
        
    }
    
    public Image getIconImage()
    {
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("Imagenes/Palomitas.png"));
        return retValue;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Titulo = new javax.swing.JLabel();
        Sailir = new javax.swing.JButton();
        Imagen1 = new javax.swing.JLabel();
        textoUsuario = new javax.swing.JLabel();
        textoContraseña = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        contraseña = new javax.swing.JPasswordField();
        btnIniciar = new javax.swing.JButton();
        Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Titulo.setFont(new java.awt.Font("Stencil Std", 1, 48)); // NOI18N
        Titulo.setForeground(new java.awt.Color(255, 255, 255));
        Titulo.setText("CINEPOLI");
        getContentPane().add(Titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 90, 260, -1));

        Sailir.setBackground(new java.awt.Color(153, 0, 153));
        Sailir.setFont(new java.awt.Font("Tekton Pro Cond", 1, 18)); // NOI18N
        Sailir.setForeground(new java.awt.Color(255, 255, 255));
        Sailir.setText("Salir");
        Sailir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SailirActionPerformed(evt);
            }
        });
        getContentPane().add(Sailir, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 20, 80, 30));

        Imagen1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/CinePP.png"))); // NOI18N
        getContentPane().add(Imagen1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, 360, -1));

        textoUsuario.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        textoUsuario.setForeground(new java.awt.Color(255, 255, 255));
        textoUsuario.setText("Usuario:");
        getContentPane().add(textoUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 440, -1, 30));

        textoContraseña.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        textoContraseña.setForeground(new java.awt.Color(255, 255, 255));
        textoContraseña.setText("Contraseña:");
        getContentPane().add(textoContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 510, -1, 30));

        txtUsuario.setBackground(new java.awt.Color(102, 0, 102));
        txtUsuario.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtUsuario.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(txtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 440, 200, 30));

        contraseña.setBackground(new java.awt.Color(102, 0, 102));
        contraseña.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        contraseña.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(contraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 510, 200, 30));

        btnIniciar.setBackground(new java.awt.Color(204, 0, 255));
        btnIniciar.setFont(new java.awt.Font("Tekton Pro", 1, 18)); // NOI18N
        btnIniciar.setForeground(new java.awt.Color(255, 255, 255));
        btnIniciar.setText("Iniciar Sesión");
        btnIniciar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnIniciarMouseClicked(evt);
            }
        });
        btnIniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIniciarActionPerformed(evt);
            }
        });
        getContentPane().add(btnIniciar, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 600, 160, 40));

        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondo.jpg"))); // NOI18N
        getContentPane().add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 410, 684));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SailirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SailirActionPerformed
        
        System.exit(0);
        
    }//GEN-LAST:event_SailirActionPerformed

    private void btnIniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnIniciarActionPerformed

    private void btnIniciarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnIniciarMouseClicked
        // TODO add your handling code here:
        
        String Usuario = "admin";
        String Contraseña = "cinepoli2019";
        
        String pass = new String(contraseña.getPassword());
        
        if(txtUsuario.getText().equals(Usuario) && pass.equals(Contraseña))
        {
            ReservaPeliculas rp = new ReservaPeliculas();
            rp.setVisible(true);
            dispose();
        }
        else
        {
            JOptionPane.showMessageDialog(this, "El usuario o contraseña estan incorrectas");
        }
        
    }//GEN-LAST:event_btnIniciarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IniciarSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IniciarSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IniciarSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IniciarSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IniciarSesion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Fondo;
    private javax.swing.JLabel Imagen1;
    private javax.swing.JButton Sailir;
    private javax.swing.JLabel Titulo;
    private javax.swing.JButton btnIniciar;
    private javax.swing.JPasswordField contraseña;
    private javax.swing.JLabel textoContraseña;
    private javax.swing.JLabel textoUsuario;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
